name: TpaPlugin
version: '${project.version}'
main: dev.rumble.tpaplugin.TpaPlugin
api-version: '1.20'

commands:
  tpr:
    description: "Solicita teletransportarte a un usuario"
  tpraccept:
    description: "Acepta una solicitud de tp"
  tprdeny:
    description: "Rechaza una solicitud de tp"