name: TpaPlugin
version: '${project.version}'
main: dev.rumble.tpaplugin.TpaPlugin
api-version: '1.20'
author: "Rumble.py"

commands:
  tpa:
    description: "Solicita teletransportarte a un usuario"
  tpaaccept:
    description: "Acepta una solicitud de tp"
  tpadeny:
    description: "Rechaza una solicitud de tp"
  tpafix:
    description: "Arregla el bug de rumble"